# TCL File Generated by Component Editor 18.1
# Wed Mar 06 00:01:26 GMT 2024
# DO NOT MODIFY


# 
# FPmult "FPmult" v1.0
#  2024.03.06.00:01:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FPmult
# 
set_module_property DESCRIPTION ""
set_module_property NAME FPmult
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FPmult
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file unnamed.qsys OTHER PATH src/IP/unnamed.qsys TOP_LEVEL_FILE
add_fileset_file unnamed.sopcinfo OTHER PATH src/IP/unnamed.sopcinfo

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file unnamed_bb.v VERILOG PATH src/IP/unnamed/unnamed_bb.v
add_fileset_file unnamed_inst.v VERILOG PATH src/IP/unnamed/unnamed_inst.v


# 
# parameters
# 


# 
# display items
# 

